---
version: "0.6.0"
description: "Deep Learning Reference Stack"
license: |
  # SPDX-License-Identifier: MIT
  # Copyright (c) 2019 Intel Corporation

stack:
  dlrs:
    version: "0.6.0"
    tag: dlrs
    ubuntu:
      version: "18.10"
      tag: ubuntu
      os_pkgs:
        - openssh-server
        - openssh-client
        - wget
        - curl
        - python37
      python:
        version: "3.7"
      tensorflow:
        mkl:
          version: "2.1.0"
          tag: tf_mkl
          flags: "CLAGS='-march=skylake-avx512 -mtune=cascadelake'"
          src:
            url: "github.com/tensorflow/tensorflow.git"
            branch: "r2.1"
        oss:     
          version: "1.15.0"
          tag: tf_oss
      pytorch:
        mkl:
          version: "1.2.1"
          tag: torch_mkl
          src: "github.com/pytorch/pytorch.git"
        oss:
          version: "1.0.0"
      horovod:
        version: "0.16.0"
    clear:
      version: latest
      release: "dlrs_clear"
      os_pkgs:
        - openssh-server
        - openssh-client
        - wget
        - curl
        - python3-basic
      python:
        version: "3.7"
      tensorflow:
        mkl:
          version: "2.1.0"
          tag: python_mkl
        oss:
          version: "1.15.0"
      pytorch:
        mkl:
          version: "1.2.1"
          tag: torch_mkl
        oss:
          version: "1.0.0"
      horovod:
        version: "0.16.0"




  

